### ISSUE TITLE
Deprecation of `np.float` in numpy>=1.24 breaks occupy

### ISSUE THREAD

**Issue by alisterburt** [bforsbe/OccuPy#12]
numpy aliases basic types have been deprecated in numpy for a while and were [removed in 1.24](https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations)

This currently breaks map loading in occupy

```ipython
Traceback (most recent call last):
  File "/Users/ahowes/soft/OccuPy/occupy_lib/occupy_gui.py", line 1440, in read_input_file
    self.set_lowpass()
  File "/Users/ahowes/soft/OccuPy/occupy_lib/occupy_gui.py", line 1973, in set_lowpass
    self.inputMap.voxel_size_ori = self.inputMap.voxel_size_proc * n/np.float(n_proc)
                                                                     ^^^^^^^^
  File "/Users/ahowes/mambaforge/envs/occupy/lib/python3.11/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'. Did you mean: 'cfloat'?
```

**Comment by alisterburt** [comment]
the correct fix is `n /  n_proc` here, will cast to float automatically nowadays :)
